### ISSUE TITLE
Uncaught TypeError: Bad argument

### ISSUE THREAD

**Issue by xiaojieluo** [skywind3000/atom-shell-commands#23]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.4.16
**OS**: "Arch Linux"
**Thrown From**: [atom-shell-commands](https://github.com/skywind3000/atom-shell-commands) package 1.5.0

### Stack Trace

Uncaught TypeError: Bad argument

```
At internal/child_process.js:289

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at exports.spawn (child_process.js:392:9)
    at execute (/packages/atom-shell-commands/lib/atom-shell-commands.js:449:14)
    at /packages/atom-shell-commands/lib/atom-shell-commands.js:52:7)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:265:29)
    at /usr/lib/atom/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:606:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:397:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/lib/atom/src/window-event-handler.js:100:36)
    at HTMLDocument.<anonymous> (/usr/lib/atom/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:58 core:save (input.hidden-input)
     -0:57.2.0 intentions:highlight (input.hidden-input)
     -0:56.9.0 pane:show-previous-item (input.hidden-input)
  7x -0:55.9.0 atom-shell-commands:run (input.hidden-input)
     -0:43.4.0 core:backspace (input.hidden-input)
     -0:43 core:move-right (input.hidden-input)
     -0:42.6.0 docblockr:parse-enter (input.hidden-input)
     -0:42.6.0 editor:newline (input.hidden-input)
     -0:39.8.0 autocomplete-plus:confirm (input.hidden-input)
     -0:36.7.0 docblockr:parse-enter (input.hidden-input)
     -0:36.7.0 editor:newline (input.hidden-input)
  2x -0:31.2.0 core:move-down (input.hidden-input)
     -0:30.8.0 autocomplete-plus:confirm (input.hidden-input)
     -0:30.4.0 intentions:highlight (input.hidden-input)
     -0:30.2.0 core:save (input.hidden-input)
  2x -0:25.3.0 atom-shell-commands:run (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-clock 0.1.13 
atom-jinja2 0.6.0 
atom-material-syntax 1.0.6 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.4 
atom-shell-commands 1.5.0 
docblockr 0.11.0 
dracula-syntax 2.0.5 
file-icons 2.1.9 
intentions 1.1.2 
language-restructuredtext 1.1.0 
language-vue 0.23.0 
language-vue-component 0.5.0 
linter-pycodestyle 2.0.2 
linter-python-pep8 0.2.0 
minimap 4.29.0 
pigments 0.39.1 
python-tools 0.6.9 
rst-preview 1.3.1 
tornado-templates 0.2.0 
```

**Comment by gm42** [comment]
It's happening because `command` should be a string, not an array.
