### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by 0814celsus** [skywind3000/atom-shell-commands#28]
I try to execute a python script in a new window in Linux 
I did as told in the manual 

[Enter steps to reproduce:]

1. "atom-shell-commands":
    commands: [
      {
        name: "terminal_python3"
        command: "./"
        arguments: [
          "~/.atom/run_python3.cmd"
          "{FileName}"
        ]
        options:
          cwd: "{FileDir}"
          keymap: ""
      }2. run_python3 looks like 
#!/bin/bash
echo $1
"/usr/bin/python3" $1
exit

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Debian GNU/Linux
**Thrown From**: [atom-shell-commands](https://github.com/skywind3000/atom-shell-commands) package 1.5.0

### Stack Trace

Uncaught Error: spawn EACCES

```
At internal/child_process.js:313

Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:399:9)
    at execute (/packages/atom-shell-commands/lib/atom-shell-commands.js:449:14)
    at /packages/atom-shell-commands/lib/atom-shell-commands.js:52:7)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1393:34)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -8:43.7.0 core:move-right (input.hidden-input)
 14x -8:43 core:backspace (input.hidden-input)
     -8:25.2.0 core:save (input.hidden-input)
     -8:12.4.0 atom-shell-commands:terminal_python3 (input.hidden-input)
  2x -7:46 core:backspace (input.hidden-input)
  2x -7:43.4.0 core:move-down (input.hidden-input)
     -7:42.9.0 core:move-left (input.hidden-input)
     -7:42.7.0 core:move-right (input.hidden-input)
  9x -7:42.3.0 core:backspace (input.hidden-input)
     -7:32.8.0 core:save (input.hidden-input)
     -7:25.4.0 atom-shell-commands:terminal_python3 (input.hidden-input)
     -6:52.9.0 core:copy (span.syntax--string.syntax--quoted.syntax--double.syntax--coffee)
  2x -1:26.6.0 atom-shell-commands:terminal_python3 (input.hidden-input)
     -0:34.3.0 core:save (input.hidden-input)
     -0:29.4.0 atom-shell-commands:terminal_python3 (input.hidden-input)
```

### Non-Core Packages

```
atom-shell-commands 1.5.0 
autocomplete-modules 1.10.0 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
file-icons 2.1.16 
git-plus 7.10.0 
hyperclick 0.1.5 
intentions 1.1.5 
linter 2.2.0 
linter-flake8 2.3.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
predawn-syntax 1.0.4 
python-autopep8 0.1.3 
python-run-terminalnx 1.1.7 
script 3.17.3 
terminal-plus 0.14.5 
```

**Comment by gallna** [comment]
Either invalid command: `./` or your script `~/.atom/run_python3.cmd` is not executable.
Run `chmod +x ~/.atom/run_python3.cmd` and modify configuration to:
```
{
  name: "terminal_python3"
  command: "~/.atom/run_python3.cmd"
  arguments: [
    "{FileName}"
  ]
  options:
    cwd: "{FileDir}"
    keymap: ""
  }
}
```
